[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "immutable-chain-map"
version = "0.0.1"
description = "A Python class similar to ChainMap, but works with any Mapping and not just MutableMapping."
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]
